### PR TITLE
Fixed some aliases

### PR DESCRIPTION
**Pull request by sebhofmann**
PERSPEC-64 the aliases now working
https://www.perspectivia.net/publikationen/pera-blaetter/1/vorhoff_aleviten 
https://www.perspectivia.net/publikationen/pera-blaetter/2/schoenig_hunnen

### CODE REVIEW

**Review by fluetze — COMMENTED** [review]
isDocumentAliasMatching() uses startsWith()
-> What if two aliases start with the same pattern?
/publications/foo
/publications/foo2

**Comment by sebhofmann** [comment]
> isDocumentAliasMatching() uses startsWith() -> What if two aliases start with the same pattern? /publications/foo /publications/foo2

The Code says:
`                    
// the longer the alias of the document is, the more likely it is the correct one
`

**Comment by fluetze** [comment]
> > isDocumentAliasMatching() uses startsWith() -> What if two aliases start with the same pattern? /publications/foo /publications/foo2
> 
> The Code says: ` // the longer the alias of the document is, the more likely it is the correct one`

... and the code guarantees that?

**Comment by sebhofmann** [comment]
> > > isDocumentAliasMatching() uses startsWith() -> What if two aliases start with the same pattern? /publications/foo /publications/foo2
> > 
> > 
> > The Code says: ` // the longer the alias of the document is, the more likely it is the correct one`
> 
> ... and the code guarantees that?

```
public class Sort {
    public static void main(String[]args){
        String longestString = Stream.of("/small", "/medium", "/very/long/path", "/xs")
                .max(Comparator.comparing((s)-> s.length(), Integer::compareTo))
                .get();

        System.out.println(longestString);
    }
}
```

Results in /very/long/path 

My Code:
```
                    Comparator<SolrDocument> compareBestMatchingAlias = Comparator
                        .comparing((doc) -> getAliasFromDocument(doc).length(), Integer::compareTo);

                    Optional<SolrDocument> bestMatchingOptionalDocument = relatedDocuments.stream()
                        .filter(MCRAliasContentServlet::documentHasAlias)
                        .filter(doc -> isDocumentAliasMatching(cleanAliasPathContext, doc))
                        .peek(MCRAliasContentServlet::logPossibleAliasDocument)
                        .max(compareBestMatchingAlias);
```
Should give the longest matching alias.

**Review by fluetze — APPROVED** [review]

**Review by rochpaul — COMMENTED** [review]
Looks good for me.

**Pull request merged**
